spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orderdb}
    username: ${SPRING_DATASOURCE_USERNAME:order}
    password: ${SPRING_DATASOURCE_PASSWORD:order}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  artemis:
    broker-url: ${SPRING_ARTEMIS_BROKER_URL:tcp://localhost:61710}
    user: ${SPRING_ARTEMIS_USER:admin}
    password: ${SPRING_ARTEMIS_PASSWORD:admin}
server:
  port: ${ORDER_PORT:8081}

app:
  jms:
    queue-inventory-reserve: order.inventory.reserve
    queue-inventory-reserve-reply: order.inventory.reserve.reply
    topic-order-events: order.events

